package com.example.grandcross;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.text.TextUtils;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

public class Registration extends AppCompatActivity {

    DatabaseReference databaseReference = FirebaseDatabase.getInstance().getReferenceFromUrl("https://grandcroos-7ee23-default-rtdb.firebaseio.com");

    EditText loginEditText, passwordEditText;
    Button registerBut;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_registration);

        loginEditText = findViewById(R.id.LoginId);
        passwordEditText = findViewById(R.id.PasswordId);
        registerBut = findViewById(R.id.LoginButtonId);

        registerBut.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                String login, password;
                login = loginEditText.getText().toString().trim();
                password = passwordEditText.getText().toString().trim();

                if (TextUtils.isEmpty(login) || TextUtils.isEmpty(password)) {
                    Toast.makeText(Registration.this, "Введите Логин и Пароль", Toast.LENGTH_SHORT).show();
                } else {
                    databaseReference.child("users").addListenerForSingleValueEvent(new ValueEventListener() {
                        @Override
                        public void onDataChange(@NonNull DataSnapshot snapshot) {
                            boolean loginExists = false;
                            for (DataSnapshot childSnapshot : snapshot.getChildren()) {
                                String existingLogin = childSnapshot.child("login").getValue(String.class);
                                if (existingLogin != null && existingLogin.equals(login)) {
                                    loginExists = true;
                                    break;
                                }
                            }

                            if (loginExists) {
                                Toast.makeText(Registration.this, "Данный логин уже используется", Toast.LENGTH_SHORT).show();
                            } else {
                                String userId = databaseReference.child("users").push().getKey();
                                if (userId != null) {
                                    databaseReference.child("users").child(userId).child("login").setValue(login);
                                    databaseReference.child("users").child(userId).child("password").setValue(password);
                                    initializeCharactersForUser(userId);
                                    Toast.makeText(Registration.this, "Вы успешно зарегистрировались!", Toast.LENGTH_SHORT).show();
                                    finish();
                                } else {
                                    Toast.makeText(Registration.this, "Ошибка регистрации, попробуйте снова", Toast.LENGTH_SHORT).show();
                                }
                            }
                        }

                        @Override
                        public void onCancelled(@NonNull DatabaseError error) {

                        }
                    });
                }
            }
        });
    }

    private void initializeCharactersForUser(String userId) {
        DatabaseReference characterRef = databaseReference.child("characters");

        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p1, R.drawable.hi1, "«Материальный Клон»`Мелиодас Лоствейн",1,0, 560, 350, 7000,40,70,0,70,170,0,60,110,10,53.9394,31.3131,704.2424, Character.Attribute.RED, userId, AbilityUtils.createAbilities(new Ability(R.drawable.ab_1_1, "«Отдельное Воздействие»``Наносит урон от отрыва, равный 264% от атаки, против цели (один враг).``*Отрыв: 3-кратное увеличение шанса на критический удар."), new Ability(R.drawable.ab_1_2, "«Тройной Аватар»``Наносит урон от заряда, равный 130% от атаки, против цели (все враги). Заражает на 1 ход(ов).``*Заряд: игнорирует оборону.``*Заражение: ограничивает связанные с восстановлением характеристики."),new Ability(R.drawable.ab_1_3, " «Материальный Клон»``Увеличивает все характеристики героя на 20% на 2 хода. Затем наносит урон от тайной техники, равный 450% от атаки, против цели (все враги) и наносит урон с помощью преимущества по свойствам вне зависимости от свойства.``*Тайная техника: +80% дополнительного урона для каждого умения героя."),new Ability(R.drawable.pas_1_1, "Уступка``Увеличивает рейтинг всех умений героя и увеличивает оборону от критического удара на 30% и до 90%, когда герой получает критический урон во время вражеского хода. Дополнительно увеличивает связанные с атакой характеристики героя на 10% на 3 хода, когда уникальная способность героя увеличивает рейтинги умения.`(Может накапливаться до 5 раз. )"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p2, R.drawable.hi2, "«Новая легенда»`Принцеса Элизабет",1,0, 520, 280, 6000,0,40,20,30,140,40,50,150,0,47.6262,40.2222,743.2323, Character.Attribute.RED, userId, AbilityUtils.createAbilities(new Ability(R.drawable.ab_2_1, "«Королевское Достоинство»``Наносит урон от наводнения, равный 143% от атаки, против цели (все враги) и восстанавливает 03 всех союзников на 30% от нанесенного урона.``*Наводнение: 0,8% дополнительного урона за каждый процент оставшегося собственного 03."), new Ability(R.drawable.ab_2_2, "«Благословенный Свет»``Снимает ослабления с цели (все союзники). Увеличивает связанные с обороной характеристики на 30% на 2 ход(ов)."),new Ability(R.drawable.ab_2_3, " «Источник Жизни»``Восстанавливает 03 цели (все союзники) в размере 504% от атаки, заполняет шкалу суперприема на сферы (2 шт.) и повышает связанные с атакой характеристики на 15% на 2 х."),new Ability(R.drawable.pas_2_1, "Тепло друг друга``В битвах PVE базовые характеристики союзников увеличиваются на 6% (до 30%) каждый раз, когда герой излечивает союзника. Шкала суперприема героя заполняется на 1 сферу, когда герой использует умение. Если герой использует умение атаки, с врага снимаются усиления до активации умения.``Во всех режимах игры степень восстановления у союзников увеличивается на 20% каждый раз, когда герой излечивает союзника. (Ограничение: 5 раз)"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p3, R.drawable.hi3, "«Королева Филориалов»`Фитория",1,0, 600, 320,6900,80,75,5,105,215,75,85,110,5,49.5252,37.3131,610.1515, Character.Attribute.BLUE, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_3_1, "Пронзающий Шторм``Уменьшает шанс на оборону от критического удара цели (один враг) на 40% на 1 ход. Затем наносит урон от отрыва, равный 200% от атаки.``* Отрыв: 3-кратное увеличение шанса на критический удар."), new Ability(R.drawable.ab_3_2, "Жестокая Буря``Наносит урон от Шторма, равный 100% от атаки, против цели (все враги).``* Шторм: игнорирует 30% от связанных с обороной характеристик.`Увеличение шанса на крит.Урон в 2 раза"),new Ability(R.drawable.ab_3_3, "Явление королевы``Даёт 2 эффекта Режущие когти герою, даёт Защиту королевы всем союзникам на 3 хода, затем наносит урон от шипа, равный 390% от атаки, против цели (все враги).``*Защита королевы:связанные с атакой характеристики +20%, связанные с обороной характеристики. + 20%``*Шип: 2-кратное увеличение крит.Урона."),new Ability(R.drawable.pas_3_1, "Правительница Филориалов``Увеличивает оборону от крит.Удара союзников на 60% на 1 ход в начале битвы. В начале хода союзников применяте власть королевы на союзников неизвестной рассы на 2 хода (не более 1 раза) и увеличивает все характеристики героя на 5% за каждого союзника неизвестной рассы участвующего в битве.`Кроме того, наносимый героем урон увеличивется на 50% при использовании Шторма. Когда союзник неизвестной рассы использует умение для нанесения урона противнику во время хода союзников, герой получает Удар королевы на 2 хода``*Власть королевы: снимает ослобление и увеличивает шанс на крит.Удар на 50%.`Увеличиваетурон, наносимый героем, на +0,3% за каждый 1% оставшихся ОЗ.``*Режущие когти: герой игнорирует 15% от сопротивления цели крит.Удару (Может накапливаться до 3 раз)``*Удар королевы: нанесённый урон +50%, шанс на крит.Удар +50%, степень пронзания +250%"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p4, R.drawable.hi4, "«Вассальное Оружие»`Глас",1,0, 530, 350, 6600,85,60,5,90,190,7,7,110,10,49.8282,35.6060,610.1515, Character.Attribute.GREEN, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_4_1, "Рондо, Нулевая позиция: Обратный Цветок Снежной Луны``Наносит урон от Кражи души равный 190% от атаки, против цели (один враг).`*Кража души: увеличивает наносимый урон на +40% за каждый действующий на героя эффект «Сила души».`2-кратно увеличивает степень пронзания." ), new Ability(R.drawable.ab_4_2, "«Рондо, Пробивная Позиция: Пролом Панциря Черепахи»``Наносит урон от пронзания, равный 200% от атаки, против цели (один враг).`*Пронзание: 3-кратное увеличение степени пронзания."),new Ability(R.drawable.ab_4_3, "«Рондо Пустоты: Лунный Разрыв»``Увеличивает базовые характеристики всех союзников на 30% на 3 хода, наносит урон, равный 400% от атаки, против цели (все враги), а затем дает 1 эффект Сила души герою."),new Ability(R.drawable.pas_4_1, "Воин Вассального Веера``Увеличивает базовые характеристики героя на 7% за каждого участвующего в битве союзника неизвестной расы. Герой получает Силу души, когда союзник неизвестной расы использует умение. И напротив, 1 Сила души снимается, когда герой использует умение. Когда снимается Сила души, степень пронзания героя увеличивается на 30%, максимум до 90%. Когда эффектов Сила души накоплен максимум, эффекты снимаются и шанс на критический удар героя увеличивается на 30%, а степень пронзания возрастает на 150% на 3 хода.``*Сила души: связанные с обороной характеристики +10%. (Может накапливаться до 3 раз. )"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p5, R.drawable.hi5, "«Алмазная Защита»`Королева Элизабет",1,0, 550, 380, 7400,90,60,5,100,190,75,80,110,5,55.0303,38.7070,616.1616, Character.Attribute.LIGHT, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_5_1, "«Изгнание»``Наносит урон от «Наказания», равный 200% ед. от атаки, против цели (один враг).``*Наказание: Увеличение степени проникновения в 3 раза.`+20% к наносимому урону на каждый действующий на себя эффект «Гнев Богини»."), new Ability(R.drawable.ab_5_2, "«Божественная Искра»``Наносит урон от «Ярости», равный 120% от атаки, против цели (все враги).``*Ярость: 1% дополнительного урона за каждый`процент оставшегося собственного 03.`+50% к наносимому урону, когда накоплено максимальное количество эффектов «Гнев Богини»."),new Ability(R.drawable.ab_5_3, "«Стена Света»``Увеличивает связанные с атакой характеристики героя на 10% на 2 хода, затем наносит урон, равный 500% от атаки, против цели (все враги), а потом применяет «Вторжение Света» на 2 хода.``Если герой участвует в битве и имеет 2 или более выживших союзников в конце хода союзников, то союзник с наименьшим количеством оставшихся 03 получает «Защиту Богини» на 1 ход. (Не более 2 ходов)``*Защита Богини: герой оживает с таким же количеством О3, какое было до гибели. (Не оживает, если гибнет от отраженного урона.)"),new Ability(R.drawable.pas_5_1, "Власть Королевы``В начале битвы накладывает на врагов эффект «Вторжение Света» на 2 хода. Увеличивает все характеристики героя на 7% за каждого применимого союзника, участвующего в битве. Кроме того, герой получает «Гнев Богини», когда применимый союзник использует умение атаки. Если герой использует умение атаки против одиночной цели с максимальным накопленным количеством эффектов «Гнев Богини», он отменяет стойки у цели и применяет оглушение на 1 ход. Затем все эффекты «Гнев Богини» снимаются.``*Вторжение Света: связанные с атакойхарактеристики: -10%`Убирает 1 сферу со шкалы суперприема при нанесении урона врагу, у которого 3 сферы и более.``*Применимые союзники: богини, люди, [Семь Смертных Грехов]``*Гнев Богини: связанные с атакой характеристики: +6% (может накапливаться до 4 раз)"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p6, R.drawable.hi6, "«Предвестник Океана»`Тармиэль из Пакта Света",1,0, 530, 420, 7600,50,40,5,70,165,50,50,110,5,43.5151,42.2121,524.2424,Character.Attribute.RED, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_6_1, "«Пронзающая Струя»``Наносит урон от наводнения, равный 200% от атаки, против цели (один враг).``*Наводнение: 0.8% дополнительного урона за каждый процент оставшихся собственных 03."), new Ability(R.drawable.ab_6_2, "«Священный Свет»``На 1 ход(ов) увеличивает атаку цели (все союзники) на 15% и, если при атаке герой получает урон, применят эффект, снижающий наносимый урон у всех врагов на 5% на 1 ход.`(Может накапливаться до 3 раз.)"),new Ability(R.drawable.ab_6_3, "Океан``Наносит урон от детонации, равный 630% от атаки, против цели (все враги).``*Детонация: 20% дополнительного урона на каждую сферу шкалы суперприема цели."),new Ability(R.drawable.pas_6_1, "Объятия Океана``Базовые характеристики всех союзников вырастают на 6% каждый раз, когда герой использует Милость для восстановления О3.`(Не более 5 р.)"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p7, R.drawable.hi7, "<Будущее Лионеса»`Принц Тристан",1,0, 620, 360, 7600, 70,50,5,50,160,60,70,100,0,46.3131,38.2121,581.1111,Character.Attribute.BLUE, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_7_1, "«Быстрое Движение»``Отменяет стойки цели (один враг) и наносит урон, равный 200% от атаки, затем оглушает на 1 ход(ов).``*Оглушение: запрещает все действия."), new Ability(R.drawable.ab_7_2, "«Триумф»``Налагает 1 эффект отвердения на цель (все союзники). Если есть ослабления, они будут сняты и будет применен 1 дополнительный эффект отвердения.``*Отвердение: +30% к сопротивлению на 3 хода. (Может накапливаться.)"),new Ability(R.drawable.ab_7_3, "«Бей Плохих!»``Наносит урон от тайной техники, равный 360% от атаки, против цели (все враги) и наносит урон с помощью преимущества по параметрам вне зависимости от параметра.``*Тайная техника: +36% дополнительного урона для каждого умения героя."),new Ability(R.drawable.pas_7_1, "Несгибаемая Воля``Увеличивает связанные с атакой характеристики союзников-демонов на 3% для каждого союзника расы демонов на поле боя. Увеличивает связанные с обороной характеристики союзников расы богинь на поле боя на 15% для каждого союзника расы богинь на поле боя."))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p8, R.drawable.hi8, "«Элитный Демон»`Зелдрис, Заповедь Благочестия",1,0, 600, 420, 7000,35,50,0,60,140,60,40,140,10,43.8181,31.6060,532.2020, Character.Attribute.RED, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_8_1, "«Указание Бездны»``Наносит урон, равный 120% от атаки, против цели (один враг) и истощает шкалу суперприема на сферу(ы)."), new Ability(R.drawable.ab_8_2, "«Стремительное Разрубание»``Наносит урон, равный 220% от атаки, против цели (один враг).`Отменяет умения восстановления на ход(ов)."),new Ability(R.drawable.ab_8_3, "«Безрассудство»``Наносит урон от шипа, равный 840% от атаки, против цели (один враг).``*Шип: 2-кратное увеличение критического урона."),new Ability(R.drawable.pas_8_1, "Командир [Десяти Заповедей]``Увеличивает базовые характеристики союзников на на каждого героя в бою с Заповедью."))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p9, R.drawable.hi9, "«Четыре Архангела»`Людошиэль, Милость Вспышки",1,0, 600, 420, 7000,85,50,0,5,120,65,15,110,10,45.4242,32.6060,540.2020, Character.Attribute.BLUE, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_9_1, "«Клинок Синего Сияния»``Наносит урон, равный 240% от атаки, против цели (один враг)."), new Ability(R.drawable.ab_9_2, "«Священный Луч»``Наносит урон от разрыва, равный 100% от атаки, против цели (все враги).``*Разрыв: 2-кратный урон против усиленных врагов."),new Ability(R.drawable.ab_9_3, "«Священный Ковчег Богини»``Наносит урон, равный 525% от атаки, против цели (все враги) и создает барьер, равный 80% от урона."),new Ability(R.drawable.pas_9_1, "Мольба о Благословении``Уменьшает связанные с обороной характеристики врагов с боевым классом ниже, чем у героя, на 40% в течение ходов в PVP.`(Применяется при вступлении в битву.)"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p10, R.drawable.hi10, "«Охотница Тундры»`Великанша Скади",1,0, 680, 450, 8100,65,60,40,70,155,55,70,120,5,40,30,510, Character.Attribute.RED, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_10_1, "«Охотничий Зверь»``Уменьшает максимальные О3 героя на 2% один раз на 3 хода, а затем наносит урон, равный 250% от атаки,против цели (один враг).`(Накапливается до 5 раз)"), new Ability(R.drawable.ab_10_2, "«Кинжал-Сосулька»``Снимает усиления с цели (один враг) и наносит урон, равный 220% от атаки."),new Ability(R.drawable.ab_10_3, "«Ледяной Взрыв»``Наносит урон, равный 540% от атаки, против цели (все враги) и восстанавливает 03 всех союзников на 30% от нанесенного урона."),new Ability(R.drawable.pas_10_1, "Холодный Взгляд``Уменьшает атаку и оборону всех врагов на и увеличивает урон от умений союзников на 15% за каждое ослабление, которому подвергается герой."))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p11, R.drawable.hi11, "«Быстрый меч»`Иноземный мастер Меча Нанаши",1,0, 580, 330, 6800,65,30,20,50,150,30,40,105,  10,41.4141,29.7070,601.2121, Character.Attribute.BLUE, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_11_1, "«Штормовая Куница»``Наносит урон, равный 220% от атаки, против цели (один враг)."), new Ability(R.drawable.ab_11_2, "«Громовой Раскат»``Наносит урон от отчаяния, равный 130% от атаки, против цели (все враги).``*Отчаяние: восстанавливает 15% от снизившегося количества 03 при каждом успешном критическом ударе."),new Ability(R.drawable.ab_11_3, "«Хлещущие Листья»``Наносит урон от возрастания, равный 945% от атаки, против цели (один враг).``*Возрастание: наносит 30% дополнительного урона за каждое активное усиление на себе."),new Ability(R.drawable.pas_11_1, "Потерянная Сила``В начале хода союзников накладывает усиление на союзников, имеющих не больше 2 карт умений, увеличивая макс. О3, сопротивление критическому удару и оборону от критического удара на 20% в течение 1 хода, чем дополнительно уменьшает шкалу суперприема атакующего врага на 1 сферу один раз за ход."))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p12, R.drawable.hi12, "«Зловещая Туманность»`Принц Тьмы Зелдрис",1,0, 560, 350, 7000,0,0,0,0,0,0,0,0,0,0,0,0, Character.Attribute.BLUE, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_3_1, "Описание способности 1"), new Ability(R.drawable.ab_3_2, "Описание способности 2"),new Ability(R.drawable.ab_3_3, "Описание способности 3"),new Ability(R.drawable.pas_3_1, "Описание способности 4"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p13, R.drawable.hi13, "«Проклятые Оковы»`Мелиодас Из Частилища",1,0, 560, 350, 7000,0,0,0,0,0,0,0,0,0,0,0,0, Character.Attribute.DARK, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_3_1, "Описание способности 1"), new Ability(R.drawable.ab_3_2, "Описание способности 2"),new Ability(R.drawable.ab_3_3, "Описание способности 3"),new Ability(R.drawable.pas_3_1, "Описание способности 4"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p14, R.drawable.hi14, "«Огонь Жизни»`Величайший Эсканор",1,0, 560, 350, 7000,0,0,0,0,0,0,0,0,0,0,0,0, Character.Attribute.LIGHT, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_3_1, "Описание способности 1"), new Ability(R.drawable.ab_3_2, "Описание способности 2"),new Ability(R.drawable.ab_3_3, "Описание способности 3"),new Ability(R.drawable.pas_3_1, "Описание способности 4"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p15, R.drawable.hi15, "«Земные волны »`Королева Диана",1,0, 560, 350, 7000,0,0,0,0,0,0,0,0,0,0,0,0, Character.Attribute.RED, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_3_1, "Описание способности 1"), new Ability(R.drawable.ab_3_2, "Описание способности 2"),new Ability(R.drawable.ab_3_3, "Описание способности 3"),new Ability(R.drawable.pas_3_1, "Описание способности 4"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p16, R.drawable.hi16, "«Искажённый тьмой»`Берсерк Эстаросса",1,0, 560, 350, 7000,0,0,0,0,0,0,0,0,0,0,0,0, Character.Attribute.BLUE, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_3_1, "Описание способности 1"), new Ability(R.drawable.ab_3_2, "Описание способности 2"),new Ability(R.drawable.ab_3_3, "Описание способности 3"),new Ability(R.drawable.pas_3_1, "Описание способности 4"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p17, R.drawable.hi17, "«Правитель»`Тиранический Король Демонов",1,0, 560, 350, 7000,0,0,0,0,0,0,0,0,0,0,0,0, Character.Attribute.DARK, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_3_1, "Описание способности 1"), new Ability(R.drawable.ab_3_2, "Описание способности 2"),new Ability(R.drawable.ab_3_3, "Описание способности 3"),new Ability(R.drawable.pas_3_1, "Описание способности 4"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p18, R.drawable.hi18, "«Семь Смертных Грехов»`Невероятный Бан",1,0, 560, 350, 7000,0,0,0,0,0,0,0,0,0,0,0,0, Character.Attribute.LIGHT, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_3_1, "Описание способности 1"), new Ability(R.drawable.ab_3_2, "Описание способности 2"),new Ability(R.drawable.ab_3_3, "Описание способности 3"),new Ability(R.drawable.pas_3_1, "Описание способности 4"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p19, R.drawable.hi19, "«Материальный Клон»`Мелиодас Лоствейн",1,0, 560, 350, 7000,0,0,0,0,0,0,0,0,0,0,0,0, Character.Attribute.RED, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_3_1, "Описание способности 1"), new Ability(R.drawable.ab_3_2, "Описание способности 2"),new Ability(R.drawable.ab_3_3, "Описание способности 3"),new Ability(R.drawable.pas_3_1, "Описание способности 4"))));
        characterRef.child(characterRef.push().getKey()).setValue(new Character(R.drawable.p20, R.drawable.hi20, "«Цельнометаллическая»`Одержимая Валенти",1,0, 560, 350, 7000,0,0,0,0,0,0,0,0,0,0,0,0, Character.Attribute.BLUE, userId,AbilityUtils.createAbilities(new Ability(R.drawable.ab_3_1, "Описание способности 1"), new Ability(R.drawable.ab_3_2, "Описание способности 2"),new Ability(R.drawable.ab_3_3, "Описание способности 3"),new Ability(R.drawable.pas_3_1, "Описание способности 4"))));

    }
}